device: cuda
train:
  batch_size: 128
  train_epochs: 90
  loss:
    - bceloss
    - regularizationloss
  optim:
    name: adam
    learning_rate: 0.001
    others:
  lr_scheduler:
    name: steplr
    others:
      step_size: 30
      gamma: 0.1
  alpha: 0.1
  model_path: ./pretrained
  progress_path: ./train_progress
  plot_epochs: 10
model:
  architecture:
    encoder:
      conv:
        - Conv2d:
            args: [1, 16]
            kernel_size: 4
            stride: 2
            padding: 1
        - BatchNorm2d:
            args: [16]
        - ReLU:
        - Conv2d:
            args: [16, 32]
            kernel_size: 4
            stride: 2
            padding: 1
        - BatchNorm2d:
            args: [32]
        - ReLU:
        - Conv2d:
            args: [32, 32]
            kernel_size: 5
            stride: 2
        - BatchNorm2d:
            args: [32]
        - ReLU:
        - Flatten:
      mean:
        - Linear:
            args: [128, 64]
        - ReLU:
        - Linear:
            args: [64, 16]
      std:
        - Linear:
            args: [128, 64]
        - ReLU:
        - Linear:
            args: [64, 16]
    decoder:
      - Linear:
          args: [16, 64]
      - ReLU:
      - Linear:
          args: [64, 128]
      - Unflatten:
          args: [1]
          unflattened_size : [32, 2, 2]
      - ConvTranspose2d:
          args: [32, 32]
          kernel_size: 5
          stride: 2
      - BatchNorm2d:
          args: [32]
      - ConvTranspose2d:
          args: [32, 16]
          kernel_size: 4
          stride: 2
          padding: 1
      - BatchNorm2d:
          args: [16]
      - ConvTranspose2d:
          args: [16, 1]
          kernel_size: 4
          stride: 2
          padding: 1
      - Sigmoid:
test:
  batch_size: 256
  model_path: ./pretrained/model_90.pt